### ISSUE TITLE
Optimize Font File Size

### ISSUE THREAD

**Issue by endico** [kmatch98/CircuitPython_memory_saving#5]
Normally I create font files that contain the entire alphabet but for applications that don't display much text, you can save space by deleting all the characters that you don't actually use. This would save ram when you do bitmap_font.load_font(), right?

See the "Optimize File Size" section here
https://learn.adafruit.com/custom-fonts-for-pyportal-circuitpython-display/conversion

**Comment by kmatch98** [comment]
There have been some recent changes to the way that fonts can be stored so I’m not 100% sure it that may affect memory use.  

As you said reducing the number of characters (sometimes called glyphs) will reduce your font file size and save on your non-volatile storage. 

As for saving RAM I’m unsure if reducing the number of glyphs will save anything. Maybe @jepler has some insights. 

I know that font glyphs are loaded on an as-needed basis, unless you “preload” the glyphs using the font.load_glyphs() command. So I’m inclined to think that by having fewer characters in the file it may not affect the RAM usage. But if your not using those characters it surely won’t hurt.

**Comment by jepler** [comment]
Subsetting your font saves space on CIRCUITPY.  If you haven't switched from BDF to PCF fonts, it saves time (but you should switch to PCF format, it saves even more time).  But (unless I overlook something) there's no "per character" data loaded until you actually call for the glyph, so subsetting a font doesn't save RAM.

**Comment by kmatch98** [comment]
I added your font space saving suggestion at the introduction where it talks about saving space on the CIRCUITPY drive.
