### ISSUE TITLE
Comments are bad

### ISSUE THREAD

**Issue by lesamouraipourpre** [kmatch98/CircuitPython_memory_saving#6]
Comments are bad
---------------------

Only joking... but they kind of are.
Comments in circuitpython code in .py format take up memory on the device when running the code even though they don't do anything. If you need to save some memory, you could delete all your comments. However, a better solution is to leave the comments in the code and compress to a .mpy file (See above/below)

But, code.py can't be compressed.

Simple workaround:
* Rename code.py to mycode.py
* Compress mycode.py to mycode.mpy on your computer and only save/copy the .mpy file to the device. This not only compresses the python scripts but removes the comments.
* Create a new code.py which imports your compressed code:
```
import mycode
```

This does make the development steps a little harder than just saving the code.py file to the device but in a memory-constrained device like QT PY it can be worth the effort.

**Comment by kmatch98** [comment]
Great suggestion! Merged in.
